SHOW databases;
USE sbl_test;

CREATE DATABASE Application;
USE Application;

SHOW TABLES;

DESCRIBE Users;
DESCRIBE Games;

SELECT * FROM Users;
SELECT * FROM Games;


SELECT ROUTINE_NAME, ROUTINE_TYPE, DATA_TYPE
FROM INFORMATION_SCHEMA.ROUTINES
WHERE ROUTINE_TYPE = 'PROCEDURE'
AND ROUTINE_SCHEMA = 'sbl_test';